# Generated by Django 3.1.4 on 2021-06-19 12:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_index"
            ),
        ),
    ]
