# Generated by Django 3.1.4 on 2021-06-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_update_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
