# Generated by Django 3.1.4 on 2021-06-20 08:47

# The pg_trgm module(using TrigramExtension()) is required
# to use the trigram similarity functions.
from django.contrib.postgres.operations import TrigramExtension
from django.db import connection, migrations


def update_car_search_word(apps, schema_editor):
    sql = """
        INSERT INTO catalog_carsearchword (word)
        SELECT word FROM ts_stat('
          SELECT to_tsvector(''simple'', model) ||
                 to_tsvector(''simple'', coalesce(description, ''''))
            FROM catalog_car
        ');
    """
    with connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carsearchword'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(sql="""
        CREATE INDEX IF NOT EXISTS car_search_word_trigram_index
            ON catalog_carsearchword
         USING gin (word gin_trgm_ops);
    """, elidable=True),
        migrations.RunPython(update_car_search_word, elidable=True),
    ]
